### ISSUE TITLE
Support streaming chat completions

### ISSUE THREAD

**Issue by mkroman** [pythops/tenere#12]
Support for streaming chat completions would be a nice addition.

Instead of waiting for a large reply, the streaming responses are more engaging.

The (unofficial) [`openai`](https://github.com/rellfy/openai) crate seems to support this.

It also uses reqwest as a HTTP client.

**Comment by pythops** [comment]
agree, that could be nice to implement

**Comment by pythops** [comment]
seems easy to fix
https://platform.openai.com/docs/api-reference/chat/create#chat/create-stream

**Comment by pythops** [comment]
Done
