### ISSUE TITLE
Model configuration value is not used

### ISSUE THREAD

**Issue by SeanAtSigma2** [pythops/tenere#17]
Hello! I was trying to set the model to `gpt-4-1106-preview` and found that it wasn't picking up the change. 

I believe the code shows a hardcoded value to `gpt-3.5-turbo`: https://github.com/pythops/tenere/blob/5109979d1949e8925cd6cb7528139c7b60e6e932/src/chatgpt.rs#L76

I'd be happy to contribute this change if you like. Or I can update the README to remove this reference of being able to set the model if you don't plan to support this functionality.

Thank you for creating an awesome tool by the way!

**Comment by pythops** [comment]
Good catch. It the value should be picked up from the config.
As you like, you can open a PR or I can fix it this evening.

**Comment by SeanAtSigma2** [comment]
Wow, I'm blown away at how fast you were able to implement that. Thank you so much again for creating such a useful tool! It's becoming a daily driver for me

**Comment by SeanAtSigma2** [comment]
For reference later: 

This was fixed by: https://github.com/pythops/tenere/commit/b27252c45c6fbb60172f927040a85812d9caa88a

**Comment by pythops** [comment]
You're welcome :) 
Glad that you like it
