### ISSUE TITLE
Issue with CLI not producing output

### ISSUE THREAD

**Issue by LLouice** [pythops/tenere#20]
First of all, thank you for your work!

After testing the CLI locally, I noticed that when using the current code at https://github.com/pythops/tenere/blob/e19682f682aeb02a9837e7e526098cea74c0005e/src/chatgpt.rs#L96, there is no output. Upon checking the raw response, I found that there is no whitespace character after `data:`, leading me to change the regex expression to `data:\s?(.*)`, which resolved the issue.

It's possible that this behavior is due to a recent change or could be a corner case, and I'm not entirely sure. Any insights would be appreciated.

**Comment by pythops** [comment]
Can you tell me which version and which model are you using ?

**Comment by LLouice** [comment]
I have tested both the release 0.9 version and the cargo build from the latest source code. I tested the chatgpt model using `gpt-3.5-turbo` and `gpt-3.5-turbo-1106`. By the way, I use a custom API URL.

**Comment by pythops** [comment]
> By the way, I use a custom API URL.

Maybe that's why. The code is following the response model from openai
https://platform.openai.com/docs/api-reference/chat/create
https://platform.openai.com/docs/api-reference/chat/streaming

Make sure that the response you get follows those guidelines and it should work.
