### ISSUE TITLE
Build breaks: error[E0282]: type annotations needed for `Box<_>`

### ISSUE THREAD

**Issue by yurivict** [pythops/tenere#29]
[log](https://pkg-status.freebsd.org/beefy18/data/main-amd64-default/p94b089c7ad30_sb162fc3f309/logs/tenere-0.11.1_4.log)

Version: 0.11.1
rust-1.80.1
FreeBSD 14.1

**Comment by pythops** [comment]
did you fetch the main branch or the code from the release ?

**Comment by yurivict** [comment]
It's for the last release.
The FreeBSD port builds the last release.

**Comment by pythops** [comment]
ah yeah, the build does not work. It is fixed in main. I will do some small refactoring and release a new version late today so you can have the fix. 

Thanks for your port :pray:

**Comment by pythops** [comment]
I have just released a new version with the fix. Give it a try and let me know if it works for you

**Comment by pythops** [comment]
@yurivict any updates ?

**Comment by yurivict** [comment]
@pythops 

The latest release builds successfully, thank you for addressing this problem very quickly.
