### ISSUE TITLE
Can't copy text from the chat (Linux)

### ISSUE THREAD

**Issue by grouzen** [pythops/tenere#30]
When I try to select a text, I don't see the usual terminal behavior that highlights a selected text, and as a result, my clipboard is empty.
Is it just me, or is it done by design? 
Thank you!

**Comment by grouzen** [comment]
Interesting, I've noticed the same behavior for `jwtui` that also uses ratatui for TUI. It might be relevant.

**Comment by pythops** [comment]
From which area you are  copying the text ?

**Comment by grouzen** [comment]
Actually, I just noticed another old issue which is still open: https://github.com/pythops/tenere/issues/11
May it be relevant?

**Comment by pythops** [comment]
yeah, it is exactly the same issue. I depend on external crate for it and  so far it is still not implemented :disappointed:

**Comment by grouzen** [comment]
Gotcha. Thanks for the answer!
