### ISSUE TITLE
provide install via Homebrew

### ISSUE THREAD

**Issue by zachvalenta** [pythops/tenere#31]
Project looks great, just thinking it would be nice to have install available via macOS package manager as well.

**Comment by pythops** [comment]
I had that option before but I was managing the tap myself and that was not ideal.
If anyone want to submit it to the homebrew official  I am fine with that :)

**Comment by Shahin-rmz** [comment]
Hi, very interesting project, specially for Vim junkies.
Is there any plans in your roadmap to include pip installation?
I want to use the project at my uni GPU Server where I do not have sudo privileges, and just can install the projects via Pip

**Comment by pythops** [comment]
@Shahin-rmz 
This is not a python project. So, even if it is possible to repackage it to install via pip, I don't think I will do it.
You can use `cargo` or download the binaries from the release page directly

**Comment by pythops** [comment]
I will close this one as no one has volunteered so far.
