### ISSUE TITLE
Make history persistent

### ISSUE THREAD

**Issue by ob7** [pythops/tenere#33]
Is the history suppose to persist between runs?  In my scenario, the program doesn't remember anything when closing and reopening.

**Comment by pythops** [comment]
yeah, it is not persistent. maybe it is good idea to make it persistent :thinking:

**Comment by 0xHumban** [comment]
Maybe you can close this issue with #40 @pythops

**Comment by pythops** [comment]
Yep, this one is completed. 
Again, thanks for the great work @0xHumban :pray:
