### ISSUE TITLE
Add to NixOS / nixpkgs

### ISSUE THREAD

**Issue by ob7** [pythops/tenere#43]
Adding tenere to nixpkgs here: https://github.com/NixOS/nixpkgs/pull/363556

**Comment by ob7** [comment]
@pythops how important is setting
```
[profile.release]
lto = "fat"
strip = true
codegen-units = 1
```
Asking for the nixpkgs related build, as it was brought up during code review:
https://github.com/NixOS/nixpkgs/pull/363556#discussion_r1876875091

**Comment by pythops** [comment]
It is good to have them cause they increase the speed of the app at the code of increase compile time

Check here https://nnethercote.github.io/perf-book/build-configuration.html#maximizing-runtime-speed

I prefer to keep them unless there is a real reason not to use them

**Comment by ob7** [comment]
@pythops- backport to nixpkgs release-24.05 is now complete, which means we can run tenere on android now via nix-on-droid.  Im running it on a unihertz titan now.  Just thought I'd mention it, as its pretty sweet to have tenere available on mobile device.

**Comment by pythops** [comment]
man, simply you rock :muscle: :fire: 
yeah would be nice to mention that. if you can write me down here how would do you do it  and I will add it to Readme, or you can open a PR if you want :pray: Plus if you can share some screencast that would be amazing :rocket:

**Comment by pythops** [comment]
maybe you can join my discord server ;) 
https://discord.gg/XYXECjU7

**Comment by ob7** [comment]
@pythops - discord invite expired, feel free to send another.  I'll make a screen recording shortly to show it off

**Comment by pythops** [comment]
https://discord.gg/mfSRc9Jann
