### ISSUE TITLE
Support more LLM

### ISSUE THREAD

**Issue by pythops** [pythops/tenere#7]

**Comment by seongs1024** [comment]
Do you have a plan to support LLAMA 2 model?

**Comment by pythops** [comment]
Yes.  I don't have much time these days but on September I'll get back more to this project to implement the promised features

**Comment by pythops** [comment]
to implement for 0.11 
https://github.com/ollama/ollama

**Comment by pythops** [comment]
Seems that llama.cpp has a server functionality
https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md
Would be interesting to add it as well

**Comment by pythops** [comment]
llama.cpp supported here #21

**Comment by pythops** [comment]
ollama  supported here #22

**Comment by pythops** [comment]
Complete
